### ISSUE TITLE
Let the player choose what server he wants the product.

### ISSUE THREAD

**Issue by strteamservidores** [Azuriom/Plugin-Shop#108]
the way it is now, if I have more than 1 server, I need to create the same product for all servers, or select only 1, is there any way to make the player choose the server he wants?

**Comment by MrMicky-FR** [comment]
Hi, this was added in https://github.com/Azuriom/Plugin-Shop/commit/a98ab3a466e1179baa090540d3dcbb58205f571e and is available in the latest release of the shop plugin 🚀
