### ISSUE TITLE
Floating point numbers like prices should be rounded

### ISSUE THREAD

**Issue by DEv0on** [Azuriom/Plugin-Shop#11]
Change price from float to double

**Comment by MrMicky-FR** [comment]
Need more details : change which price ? And any reason to change it ?

**Comment by DEv0on** [comment]
https://imgur.com/a/BYRAmnI

**Comment by MrMicky-FR** [comment]
It's not possible to change the type of a float to a double because in PHP there is no difference between these 2 types, but I'll correct this
