### ISSUE TITLE
Adding Polish payment gateways such as paybylink.pl cashbill.pl etc

### ISSUE THREAD

**Issue by Patryczeqq** [Azuriom/Plugin-Shop#110]
Adding Polish payment gateways such as paybylink.pl cashbill.pl etc
Paybylink.pl API documentation: https://paybylink.pl/partner/dokumenty/
Cashbill.pl API documentation:
https://www.cashbill.pl/pobierz/api/

**Comment by MrMicky-FR** [comment]
Hi, thanks for your suggestion :)

Unfortunately it would be too complicated for us to add and test country-specific payment gateways in the shop for every countries.

The best solution would be to create a small plugin to add this payment method, like we did for Dedipass (a french payment gateway) with this plugin: https://github.com/Azuriom/Plugin-DedipassPayment.
