### ISSUE TITLE
Improvements in Gift-Cards

### ISSUE THREAD

**Issue by jotiprime** [Azuriom/Plugin-Shop#114]
Add an option to allow the user to customize the balance of the gift card according to the balance of the package.

**Comment by Jotiprime** [comment]
Now gift-cards are the same transfer system, will be good to allow you to buy cards with real money and the cards generate internal money, so will be no way to cheat with multi accounts. (Allow to choose in general in all packages to be purchased with external and internal money and this will include gift-cards)

**Comment by Jotiprime** [comment]
Log in "Edit Gift-Card" The action of redeeming the card.

**Comment by Jotiprime** [comment]
Add feedback when redeeming a card in: your payments.

**Comment by Jotiprime** [comment]
Add discord Webhook when a card is redeemed.
