### ISSUE TITLE
Coupons not showing when are already used.

### ISSUE THREAD

**Issue by jotiprime** [Azuriom/Plugin-Shop#116]
Hi, in admin panel, in Coupons, we can see Enabled and Active, if a coupon have a user limit and this limit is reached, it stay saying active and enables "yes". Need to say in Active no, when cupon can not be used more, if not how I can know that I can delete the coupon or that the coupon has been used?

Also will be good than in the email shows that you used the coupon or gift card.

![image](https://user-images.githubusercontent.com/73477224/220453705-baacd3d2-9bc9-4ee5-a9fd-17ac436742ed.png)
![image](https://user-images.githubusercontent.com/73477224/220453736-6313e3f6-ac27-40e7-b3bd-d279108dab33.png)

**Comment by Jotiprime** [comment]
![image](https://user-images.githubusercontent.com/73477224/220456331-b82e02af-a8a7-4e69-a48c-6556879c91ea.png)
![image](https://user-images.githubusercontent.com/73477224/220456370-38b863f7-b4e0-4c5e-a383-1b437d7715d7.png)


![image](https://user-images.githubusercontent.com/73477224/220456389-44da7f7a-5322-41a5-948f-811e31776b3c.png)
![image](https://user-images.githubusercontent.com/73477224/220456396-799ffafa-4271-48a7-9bcf-2612c3cd473d.png)

Just see screenshots

**Comment by Jotiprime** [comment]
Also will be good to inculde cupon log in edit coupon page. (same as gift-card)
