### ISSUE TITLE
Coupon issue.

### ISSUE THREAD

**Issue by Jotiprime** [Azuriom/Plugin-Shop#118]
I can put a Cupon that is not enabled to specific package (it charge the correct amount without discord) Visual bug.
![image](https://user-images.githubusercontent.com/73477224/220479448-28a60549-5b2b-44fa-bc00-d73ef66973d0.png)

**Comment by MrMicky-FR** [comment]
This seems expected : you can add a coupon to a cart even if it doesn’t apply yet, but as soon as corresponding packages are added, the coupon will apply

**Comment by Jotiprime** [comment]
Okay, thanks
