### ISSUE TITLE
Paysafecard test failed

### ISSUE THREAD

**Issue by haeiven** [Azuriom/Plugin-Shop#12]
Hello,

It seems the Paysafecard integration do not pass the test.

![a4a24633d1775e5aaa839c18634aa669](https://user-images.githubusercontent.com/11612016/96912592-e558ed80-14a2-11eb-950a-fda83b4c16e8.png)

Best regards,

**Comment by MrMicky-FR** [comment]
Hi,

Make sure that you use the latest version of the plugin and then make sure you don't have a proxy (like Cloudflare) that could block the paysafecard request, or if it's the case make sure to whitelist the API URLs (`/api/*`).

If you still have the problem after this, you can join our [Discord server](https://azuriom.com/discord) for easier support 😃
