### ISSUE TITLE
Subsciption to product

### ISSUE THREAD

**Issue by ItzT0kyoo** [Azuriom/Plugin-Shop#124]
------ EN ------
Add a possibility to activate the "Subscription" mode which allows the player to pay a monthly subscription with the options: 
- The command(s) to be made when subscribing to a purchase.
- The command(s) to be made every renewal time.
- The command(s) to be made at the end of a subscription.
------ FR ------
Ajouter une possibilité d'activer le mode "Abonnement" qui permet au joueur de payer un abonnement mensuel avec les options : 
- La (les) commande(s) à effectuer lors de la souscription d'un achat.
- La (les) commande(s) à effectuer à chaque renouvellement.
- La (les) commande(s) à effectuer à la fin d'un abonnement.

**Comment by MrMicky-FR** [comment]
Duplicate of #31
