### ISSUE TITLE
Add Xendit payment gateway

### ISSUE THREAD

**Issue by SnailCrazy** [Azuriom/Plugin-Shop#13]
Hi, i like how this CMS work together, but with limited option for payment gateway can you add Xendit as a payment gateway?

short detail about [Xendit](https://xendit.co) is a payment gateway located at Indonesia

**Comment by MrMicky-FR** [comment]
Hi,
I understand that the current gateways may not be suitable for some countries (even though there are already 7 gateways), unfortunately it would be too complicated for us to add and test country-specific payment gateways in the shop: for example for Xendit just to create an account you have to be in the Philippines or Indonesia which is not our case.
The best solution would be to create a small plugin to add this payment method, like we did for Dedipass (a french payment gateway) with this plugin: https://github.com/Azuriom/Plugin-DedipassPayment.

**Comment by SnailCrazy** [comment]
Ok i see, but i can tell how about add a Manual Payment, so we can write how to pay

**Comment by MrMicky-FR** [comment]
Yes manual payments could be implemented, you can open an issue for this suggestion if you want 😀
