### ISSUE TITLE
[Suggestion] Shop Improvement & Tebex integration

### ISSUE THREAD

**Issue by Ninatasia** [Azuriom/Plugin-Shop#130]
## Hello to all of you.

For those who have a FiveM server, you may know that FiveM (CFX) forces FiveM server managers to use Tebex if they want to create a store for their server.

Everyone who has created a FiveM store knows how annoying it is, because there are many taxes and fees to pay. Here is an example with a payment of 10€ via PayPal made on Tebex (the amounts are taken from the French legislation (VAT, company contributions) and the Tebex doc).

## Unpacking revenue on Tebex
|**Labels**|**Tax & Fees**|Deducted amount|Amount left|
|:--:|:--:|:--:|:--:|
|VAT charged|22%|1,80€|8,20€|
|Paypal|2,49%**¹** + €0,40|1<br>0,61€(~0,21€ + €0.40€)|7,59€|
|Tebex|5%|0,38€|7,21€|
|CFX (FiveM)|15%|1,08€|6,13€**²**|
|Urssaf**²**|22%|1,35€|4,78|

**¹**Tebex shows 0.61€, I get 0.60€, I think they round up to 2.5% for Paypal.
**²**In France, revenues must be declared.

|Before|After|Difference|
|:--:|:--:|:--:|
|10€|4,78€|5,22€|

Is that enough? Not at all, you have to add £12.49 or about 14,11€ for the "Tebex Plus" Plan which allows you to unlock a lot of tools to keep your players loyal etc...

Knowing that not all FiveM servers generate a lot each month, and that you often have to add at least 15€ for the cheapest FiveM license if you want to add modded clothes on the server, and get two or three other "advantages" in addition.

So Azuriom would be a real plus for many servers to save some money.

Now that I've given you a big headache with all this, I can now move on to presenting my two ideas. 🤣

### Linking Azuriom to the Tebex API

The goal is to use Tebex as a new payment platform.
After each purchase made on Tebex, the platform sends an invoice by email to the person who made the purchase.
On this email, you will find various information such as the amount paid and the TransactionID (ID of the invoice).

It would therefore be necessary to create a module similar to "PaySafeCard", i.e. once the purchase is made, the player will have to retrieve the TransactionID which will act as a sort of PaySafeCard code. The system will communicate with the Tebex API to retrieve the amount billed to the player in order to credit him with the correct number of credits (for example, 1€ = 1 credit and 4.99€ = 4.99 credits).

If possible, the site (Azuriom) will check every X minutes if an invoice has been edited on Tebex, if a new invoice has been made, Azuriom will check if the person is registered or not, if the person is registered then the credits will be added automatically to his account, otherwise the player will have to fill out the form after registration to claim the store points.

This could be two payment modules "Tebex - Automatic" and "Tebex - Manual".

In the event that the automated system is possible, then it would allow the player to credit his account automatically every month via Tebex.

### Configurable subscriptions

It would be great to allow adding a subscription system on packages.
By default nothing will be enabled, so you will have to enable the payment cycles you want to accept on a package.

**Possible cycles :**
- Weekly & Bi-Weekly (1 & 2 weeks)
- Monthly, Bimonthly, Quarterly & Semi-Annual (1, 2, 3 & 6 months)
- Annual & Bi-Annual (1 & 2 years)

This is good but is it automatically renewable? No, by default it will not be automatically renewed, so you have to check "Enable automatic renewal".
If no cycle is checked but the option of automatic renewal is checked then by default it will be Monthly.

It might even be interesting to create groups of predefined cycles and just select the right group (faster).

### Better subscriptions

Building on the second idea, subscription cycles could give players discounts over time.
Kind of like with various companies offering subscriptions, the longer you subscribe the better the discounts will be. On Azuriom it should be the same.

Why do it ? Well, it helps to keep the players who support the server.

### Sponsorship

The sponsorship system, it is done more and more and for good reason it allows to reward people who advertise us, so a sponsorship code, a reward for the sponsor and for the godchild and it's done!

## Thank you for reading 👋
Thank you for reading my huge pamphlet.
I hope you like these ideas.

I also specify that the idea of subscriptions has already been done but here it is a more advanced version, which does not seem to have been shared on GitHub. It has been shared on your Discord server by another community member whose nickname is BeeStyle, he wanted it to be shared :

In French (Original) :
> Par contre je n'ai pas de compte Github et je n'en ai pas besoin de façon général, donc si quelqu'un en as un et apprécie l'idée ça serait top que ça soit officiellement suggéré sur Github.

In English (Translated) :
> But I don't have a Github account and I don't need one in general, so if someone has one and likes the idea it would be great if it was officially suggested on Github.

Link of his message : https://discord.com/channels/625774284823986183/625777292052004916/1099268818058092545

**Comment by MrMicky-FR** [comment]
Hi, first of all thank you for this detailed suggestion, it’s truly appreciated!

I’m closing this as the first suggestion should be made in the Tebex plugin for Azuriom, and the others suggestions are already existing issues (#31 and #88). 

However as your suggestion adds interesting context for the existing ones, it could be great to add comments on the corresponding open issues!

I hope you understand, as one big meta-issue makes tracking much more difficult especially for duplicated ideas 🙂

Thanks again for your time!

**Comment by Ninatasia** [comment]
The two suggestions mentioned in your message are very different, they are not as complete.

Moreover I put 4 ideas, you only put two suggestions already posted. I think Azuriom really wanted to improve more and more and attract more people. 😞

**Comment by MrMicky-FR** [comment]
> The two suggestions mentioned in your message are very different, they are not as complete.

My answer may have been unclear,  but what I meant to say is for ideas with existing issues, you should add comments on the related issues because otherwise it’s complicated for development tracking to have multiples issues for the same idea

> Moreover I put 4 ideas, you only put two suggestions already posted. I think Azuriom really wanted to improve more and more and attract more people. 😞

Please re-read my comment, for the 4 ideas : 
1. This should be a suggestion for the [Azuriom Tebex plugin](https://market.azuriom.com/resources/85)
2. Issue #31
3. This is an extension of idea 2, so it should be with it as it’s not possible to implement this until subscriptions are added
4. Issue #88

I hope it’s better now, tell me if something isn’t clear :)

**Comment by Ninatasia** [comment]
Well, I'll see about adding my suggestions to the existing suggestion topics.
Have a great day.
