### ISSUE TITLE
Add an option on the role for discounts and coupons

### ISSUE THREAD

**Issue by IkiaeM** [Azuriom/Plugin-Shop#132]
Add an option where you can select the role for which the reduction will have effect.

The idea is to have the possibility to apply an automatic discount in the shop when the player has the role selected.

And the same thing with the coupon codes.
Limit the possibility to use a coupon if the player has not the role defined.

**Comment by MrDoudou** [comment]
@IkiaeM Tu veux une remise automatique ou verrouiller un code promo uniquement a un role ?

**Comment by IkiaeM** [comment]
The 2 options.

An automatic discount if you have the roles for the "discount" option and a locker promo code has a role.
