### ISSUE TITLE
Be able to manually increase the received amount or even manually write donations.

### ISSUE THREAD

**Issue by KvasirQc** [Azuriom/Plugin-Shop#140]
Hello,

For the shop,I would like to have the ability to modify the amount received in the donation goal. I would greatly appreciate being able to increment or decrement (if I express it correctly) in order to make it easier for the admin to modify the amount of money received, as if, for example, they had received the money previously or from another platform without the Azuriom link, or even manually write donations for the donation tables!

Would this be possible, please? Thank you very much.

_____

Salut,

Pour la shop, nous avons l'options de modifier le montant recu dans le donation goal. J'apprécierais BEAUCOUP, pouvoir incrémenter ou décrementer (si j'exprime bien) pour pouvoir donner la peine a l'admin de modifier le nombre d'argent recu, comme si par exemple il avait recu l'argent auparavant, ou d'une autre plateforme sans le link azuriom ou même écrire manuellement des donations, pour les tableaux des donations! 

Serait-ce possible svp ? merci beaucoup

**Comment by KvasirQc** [comment]
Another way to see it. If I had manually cash to someone account, and they buy a rank or whatever, the amount of the purchases won't be added to the  Goal of the month. That could be a quick fix for me.

That would be great if it will be added to the donator list too!

**Comment by MrMicky-FR** [comment]
Closing in favor of #125
