### ISSUE TITLE
Ajout d'un champ personnalisé pour les acheteurs

### ISSUE THREAD

**Issue by WhiteWolf9653** [Azuriom/Plugin-Shop#141]
Mon idée consiste à ajouter un champ personnalisé dans le processus d'achat (comme l'input pour les codes promos), où les acheteurs pourraient saisir des informations spécifiques. Ce champ pourrait être un simple champ de texte libre ou un champ de numéro.

Ensuite, lorsqu'une commande est passée avec ce champ rempli, j'aimerais que les informations saisies par l'acheteur soient récupérées et incluses dans la commande qui est envoyée au serveur avec le RCON ou AzLink. Ceci pourrait être réalisé en utilisant une balise de substitution, telle que "{nomDeL'input}", qui serait remplacée par le contenu de ce champ personnalisé.

Ma suggestion principale consiste à ajouter un champ personnalisé lors du processus d'achat, permettant aux acheteurs de fournir des informations supplémentaires importantes pour le traitement de leur commande. Par exemple, si votre serveur nécessite un "Id Boutique" spécifique (un identifiant défini en jeu) pour attribuer un produit, l'acheteur pourrait simplement saisir cet Id Boutique dans le champ personnalisé.

Il serait également utile de permettre aux vendeurs de gérer ce champ personnalisé. Ils devraient pouvoir définir le titre du champ, choisir entre un champ de texte ou un champ numérique, et décider s'il est obligatoire ou facultatif pour les acheteurs. Cette flexibilité donnerait aux vendeurs un meilleur contrôle sur les informations qu'ils souhaitent collecter lors du processus d'achat.

**Comment by MrMicky-FR** [comment]
Duplicate of #53
