### ISSUE TITLE
Add an independent permission to change only the packages, another for coupons, another for discounts...

### ISSUE THREAD

**Issue by joti-prime** [Azuriom/Plugin-Shop#143]
Add more permissions, I don't like that people can see payment gateways. But maybe I want them to change the products/items.

**Comment by MrMicky-FR** [comment]
This feature is now available in the private beta of the shop plugin, which also include subscriptions with automatic renewals. See the announcement on our [Discord server](https://azuriom.com/discord) for details and beta access 🚀
