### ISSUE TITLE
Management of the number of items for sale

### ISSUE THREAD

**Issue by LePirateYTB** [Azuriom/Plugin-Shop#144]
The goal would be to be able to sell to the right number. Example in stock I have 8 luxury items for sale on my server, so 8 people can buy it. When a person buys this, they get one a each time.

thanks you !

**Comment by MrMicky-FR** [comment]
After some consideration and lack of demands are not planning to integrate this in the near future

**Comment by HC-Emro** [comment]
Il me faut également la possibilité de mettre des stocks sur ma boutique. S'il vous plaît !
