### ISSUE TITLE
Add a text box so users can enter something and this will be a variable.

### ISSUE THREAD

**Issue by joti-prime** [Azuriom/Plugin-Shop#149]
Allow an option that allows users to put text/numbers and this is set as a variable and send it through the command line (rcon)

**Comment by MrMicky-FR** [comment]
Duplicate of #53

**Comment by MrMicky-FR** [comment]
It’s already the third time you open a duplicate issue just for the shop plugin, please make sure to check for the existing issues before opening a new one (there is 15 open issues, shouldn’t take much time), thank you 😊
