### ISSUE TITLE
Sometimes the payment is sent twice

### ISSUE THREAD

**Issue by RSLuke** [Azuriom/Plugin-Shop#150]
It only happened once that I've seen but the object was sent in the game twice, the player made a 15€ payment for 2 different articles and recieved both articles twice. Happened for a Minecraft server with Stripe on the 12th of July.

**Comment by MrMicky-FR** [comment]
We would need more information on how to reproduce this issue so we can investigate

**Comment by RSLuke** [comment]
Of course but what information could I give you

-- 

Je peux également répondre en français.

**Comment by MrMicky-FR** [comment]
The steps on how we could reproduce this issue on our installation to figure out the cause and fix it
