### ISSUE TITLE
Change image of payment methods

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Shop#152]
When we set up the payment methods, the logo images come automatically.

![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/42e3b003-b01a-4830-970f-1eca26ad5f95)

It would be interesting to have the option to let the admin change these images if you don't want to use the images that come by default.

**Comment by MrMicky-FR** [comment]
PayPal and PayPal Express Checkout aren’t designed for simultaneous use
