### ISSUE TITLE
[Enhancement] Some ideas for enhancing the plugin

### ISSUE THREAD

**Issue by NoltoxGit** [Azuriom/Plugin-Shop#154]
### Description of my suggestion

[🇫🇷] Saluut !
En regardant quelques options disponibles sur les différents sites de shop disponible j'ai trouver quelques idées qui pourraient être intéressantes dans ce plugin :
- Quand la connexion Microsoft est activé, demander l'email (obligatoire) avant de pouvoir procéder au paiement
- Dans la page des paramètres, faire en sorte qu'on puisse activer/désactiver l'utilisation d'une carte cadeau
- Dans la page des paramètres, faire en sorte qu'on puisse activer/désactiver l'utilisation d'un code de promotion

[🇬🇧] Heelloooo !
Looking at some of the options available on the various shop sites available I found a few ideas that might be interesting in this plugin :
- When the Microsoft connection is activated, ask for the email (mandatory) before proceeding to payment
- In the settings page, enable/disable the use of a gift card
- In the settings page, enable/disable the use of a promotion code

------

~ Noltox ~

**Comment by MrMicky-FR** [comment]
> When the Microsoft connection is activated, ask for the email (mandatory) before proceeding to payment

This can be achieved by enabling email verification in the email settings
