### ISSUE TITLE
Error when paying with PayPal payment method

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Shop#158]
I configured both PayPal payment methods, but both give errors when making the payment.

**PayPal** option configuring only the PayPal error email: `An error occurred. Please try again later.`

![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/9aac168f-4176-4fda-92a6-3bed59a75cb5)

Option **PayPal Express Checkout** I configured the credentials and key that asks for it, but it also gives an error: `500 Server error`

![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/30ddeb33-de75-4cf5-8ae2-ab074073716b)

My PayPal account is using the **`Sandbox API credentials`**. Do I need to update **`Live credentials`** for it to work?

If my account needs to be **PayPal Business**?

Error log:
[laravel-2023-09-12.log](https://github.com/Azuriom/Plugin-Shop/files/12588580/laravel-2023-09-12.log)
[laravel-2023-09-11.log](https://github.com/Azuriom/Plugin-Shop/files/12588581/laravel-2023-09-11.log)

**Comment by MrMicky-FR** [comment]
> My PayPal account is using the Sandbox API credentials. Do I need to update Live credentials for it to work?

Yes
