### ISSUE TITLE
Gateways PayPal | Do not accept payment if you do not provide your primary email

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Shop#162]
I did the test by entering my secondary PayPal email in the PayPal payment options in Shop, the user completes the purchase but there is an error in the order, the order is generated but there is an error but the payment still comes to the PayPal account.

Due to this error I receive the money but the user does not receive the products in their account.

Would it be possible to implement that it doesn't even accept payment in the store?

I understand that the simple solution would be to inform the main email. But it would not be possible to implement a "security" mode, let's say, refuse payment and so on.

**Comment by MrMicky-FR** [comment]
Unfortunately I'm not aware of any way to verify if the email is the primary or not.

That's why it's clearly indicated during the setup process in the admin dashboard:
![](https://github.com/Azuriom/Plugin-Shop/assets/30863452/6aaaa473-faae-4c40-ad35-affbb9debc73)
