### ISSUE TITLE
Pending PayPal Error again

### ISSUE THREAD

**Issue by Razorxd1993** [Azuriom/Plugin-Shop#167]
Hello dear Azuriom Team :)

If an order has been triggered via PayPal, this remains in the database with the status pending.
If you place a free order, it goes through without any problems.

Image from the database:
![Screenshot_2023-12-12-23-00-06-335-edit_com android chrome](https://github.com/Azuriom/Plugin-Shop/assets/64865874/91d7a9fe-7b1a-47ee-81f9-932fc25bef34)

This error already existed once in this request:
https://github.com/Azuriom/Plugin-Shop/issues/54

Kind regards

**Comment by MrMicky-FR** [comment]
This expected until the payment on PayPal is completed. If the status isn’t updated after a payment make sure to see the FAQ in our documentation, as this might be caused by a proxy/firewall blocking PayPal pingbacks.
