### ISSUE TITLE
Suggestion - Parametrage des permissions de la Boutique

### ISSUE THREAD

**Issue by LesConseilers** [Azuriom/Plugin-Shop#168]
Idée : 
Il serait bien de pouvoir modifier entièrement les permissions de la boutique, notamment avec les catégories. En effet, pour modifier une catégorie, il faut avoir accès à tout le shop afin de pouvoir modifier une catégorie, ajouter un produit, modifier le prix, etc...
Je pense donc qu'il serait bien de pouvoir ajouter une personne à une catégorie de la boutique.
Exemple : J'ai une catégorie A ou je vend un item B & C. J'ai une catégorie Z ou je vend un item X & Y. Je veux ajouter un responsable de la boutique A, alors, je lui donne accès uniquement à la catégorie A et moi, je continue de gérer la catégorie Z.

Avantages : 
Cela permettrais aux serveurs ayant sous serveur "Exemple : PvP Faction" de pouvoir avoir des personnes pour gérer la partie de leur boutique sans avoir la possibilité de modifier les boutiques des autres serveurs, ou encore, rediriger le moyen de paiement vers un compte tiers (Exemple : Son PayPal personnel)

**Comment by MrMicky-FR** [comment]
Duplicate of #143

**Comment by MrMicky-FR** [comment]
Added in version 1.2.0 of the shop :)
