### ISSUE TITLE
PaySera support

### ISSUE THREAD

**Issue by dexasz** [Azuriom/Plugin-Shop#17]
Would be pretty cool if the shop plugin could support https://paysera.com - most commonly used by the baltic countries, but you can see them being supported in other sites, they also support sms payment methods, bank payments, etc.

**Comment by MrMicky-FR** [comment]
Hi, thanks for your suggestion :)
Unfortunately we don't plan to add new payment methods for now. However, if you want you can create a small plugin to add this payment method, like we did for Dedipass (a french payment gateway) with this plugin: https://github.com/Azuriom/Plugin-DedipassPayment.
