### ISSUE TITLE
New Gift cards not working

### ISSUE THREAD

**Issue by RSLuke** [Azuriom/Plugin-Shop#179]
FR

Si un utilisateur utilise le code d'une carte cadeau et que le montant payé passe à 0, on lui propose tout de même de choisir un moyen de paiement ensuite, puis sur le moyen de paiement, le montant initial est affiché, pas 0.

EN

If a user redeems a gift card code, and the paid amount becomes 0, they are still prompted to choose a payment method afterward. On the payment method screen, the initial amount is displayed, not 0.

![Capture d'écran 2024-03-05 110710](https://github.com/Azuriom/Plugin-Shop/assets/1693933/9859c67d-8846-4bd8-86b8-bf402818687a)

**Comment by RSLuke** [comment]
Hello,
Vous êtes au courant que ça ne fonctionne toujours pas ?

**Comment by MrMicky-FR** [comment]
Le problème a normalement été corrigé, s'il y a encore un problème il faudrait détailler ce qu'il se passe

**Comment by RSLuke** [comment]
Aucun changement par rapport au post initial
Essayé sans thème, pas de changement.
Essayé sur plusieurs moyens de paiement (même si à priori ils n'auraient pas dû s'afficher), toujours le montant initial sans prendre en compte la carte cadeau
J'utilise bien la dernière version d'Azuriom et la v1.1.10 du Plugin Shop
Je suis dispo pour faire des tests au besoin

**Comment by RSLuke** [comment]
J'ai fait ces tests avec une carte cadeau de 10€ sur un produit de 10€, puis avec Stripe & Mollie
J'ai également essayé à l'instant avec une carte cadeau de 9€ sur un produit à 10€, le montant n'est pas actualisé sur les moyens de paiement

**Comment by MrMicky-FR** [comment]
Effectivement, le problème est déjà corrigé dans la version béta du shop en attendant la release stable
