### ISSUE TITLE
Support for adding products to the store without description

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Shop#181]
I'm trying to add a product to the store, without a description, but it's not possible because it gives an error saying that the product needs to have a description.

Would it be possible to add products to the store without a description as non-mandatory?

In my case, the category I want to add a product to already has a general description, it would be the same for all products, so without the need to add a description for each product in this category.

**Comment by MrMicky-FR** [comment]
Unfortunately it wouldn’t be possible as description is required by some payment gateways to provide details on the purchased items
