### ISSUE TITLE
Add option to select multiple servers at the same time to deliver the product

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Shop#182]
The latest version of Shop no longer allows you to select multiple servers at the same time to deliver the product. As I mentioned on discord and received feedback from the developers.

![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/85500d11-559a-4dfd-8378-2d7408d2e37f)

I even understand the point, freedom to choose different commands for different servers, etc. But I believe we can still have the ability to select multiple servers for the same product.

An example that applies to my store, I have a product that would be for all servers and executes 3 commands on all servers in this case.

![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/5c6b4fa8-08c9-41fd-ac6f-3c6973b71d36)

In these 3 commands I would like to include all my servers, you can imagine the problem if I have more than 5 game servers. In other words, I need to include 3 commands for each of the servers.

There is a huge list in the web interface, working through it is repetitive and tiring, and if you could select several servers for the same command, it would solve my issue.

That's the question, why not also include the option to select multiple servers if I want in the same command in addition to having the option to select just one exclusive command for another server.

**Comment by crashzk** [comment]
@MrMicky-FR I believe it has not been implemented.

![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/4e3eaa98-2a4f-40f5-b600-52b153693247)

I can select multiple commands for the same server, but I cannot select multiple servers for the same command.

**Comment by MrMicky-FR** [comment]
It solves the same issue, instead of having one box per command per server, you only need one box per server

**Comment by crashzk** [comment]
> It solves the same issue, instead of having one box per command per server, you only need one box per server

Sorry, I don't understand... How can I select several servers at the same time to receive the same command?
![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/1eeeece2-6707-457b-b9ac-90badc9c5c88)

**Comment by MrMicky-FR** [comment]
You cannot, but to take the original issue, if you have 3 commands to dispatch on 5 servers, when before you would have needed 15 « command boxes », you now only need 5 so the issue is fixed :)

**Comment by crashzk** [comment]
Yes, tendi... Now in the case of selecting multiple servers for the same command, it would be a new request.

Got it, I'll open an issue focusing on this then, thank you.

**Comment by MrMicky-FR** [comment]
But what’s the point as the original issue is solved?

**Comment by crashzk** [comment]
In this case it solved a problem, several commands for the same server. So far so good.

The real problem would be one command, for several servers.

For example, in my store I sell VIP, but I have more than 5 servers and only growing.

When the user buys VIP I send the command `!vipadd "STEAMID" ...` to the servers. However, as I can only select one server at a time, I need to execute this same command for all 5 servers, resulting in a large list.

![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/0b96f63e-e72d-45a6-8735-f48bc2c77b7a)

As you can see in the print, 3 servers all run the same command, that's just 3 servers. Imagine how I said a list with 5 servers or more. And this command is only for purchases, if the user is refunded I send another command to each server to remove.

That is, if I create the same command 10 times to add VIP on each server, I need 10 more commands just to work in case of a refund.

A simple solution would be, in the option to select servers that will receive the commands, you can select more than one at the same time.
![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/aa338177-3acb-411d-af95-f73271ba81bb)

This way, the add VIP command is configured just once and is sent to all servers, instead of creating one by one for each server.

(Did you understand, sorry for the terrible English, using Google Translate)

**Comment by MrMicky-FR** [comment]
I see, but it would add too much complexity for very little gain as usually there isn’t dozens of servers 😅

**Comment by crashzk** [comment]
> I see, but it would add too much complexity for very little gain as usually there isn’t dozens of servers 😅

I understand, it really "breaks" me down, I would have several servers. 🥸

Anyway, I'll look for a better way then.
