### ISSUE TITLE
Option to add images to products

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Shop#186]
Currently we can place a photo for each product you register in the store and the description also includes images.

![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/08abe8be-b2cf-4b50-bc42-0b9a464a3a16)

I believe it would be interesting to include an option to add several images, rotate the images in a carousel/loop and below the product description.

So in addition to the description, we can include some photos to show more of the benefits of the products.

Example:

> ![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/62faf131-bcd2-4b9a-8fdc-2c07fe0d3ecb)

**Comment by crashzk** [comment]
Or can this modification be applied to the direct theme?

**Comment by MrMicky-FR** [comment]
You can already add multiple images (and even videos) in the product description by using the image icon in the description’s editor :)

**Comment by crashzk** [comment]
I tested it with the direct link.

![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/8c33cd3c-3c5e-4966-a182-7cbad3dea916)

That wouldn't be the case, in this case I would like to show one image at a time and just move them to the side.
