### ISSUE TITLE
Chargebacks/refunds not updated 

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Shop#188]
After a payment for the product is made the status is marked as **Completed**.

![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/703d81c0-05ef-4cc8-81cf-ba7e992bc73f)

However, in the case of a **Refund** or **Chargeback**, this status does not update.

This payment was even a payment refund but the status is still marked as **Completed**.

**Comment by crashzk** [comment]
I don't know if it had anything to do with it, but I received this error log too.

[laravel-2024-03-29.log](https://github.com/Azuriom/Plugin-Shop/files/14809624/laravel-2024-03-29.log)

**Comment by MrMicky-FR** [comment]
With which payment gateway do you have this issue ?

**Comment by MrMicky-FR** [comment]
According to your screen it’s with Mercado Pago, in this case it’s an issue with the MercadoPago payment gateway, so you would have to report this issue to its developer

**Comment by crashzk** [comment]
> With which payment gateway do you have this issue ?

Mercado Pago, I'll be talking to the payment gateway developer, so I'll get back to you with anything.

I will also be testing with those that already come with the Shop plugin as well.

**Comment by crashzk** [comment]
@MrMicky-FR I used PayPal, the user made the payment normally, everything was fine, he was charged.

However, the Azuriom panel did not register the purchase on PayPal and generated an error log.

However, after a few minutes the sale registered, would it be normal?

[laravel-2024-03-30.log](https://github.com/Azuriom/Plugin-Shop/files/14812378/laravel-2024-03-30.log)

![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/a4f8decf-0047-4658-a0aa-ae012a94a329)

Then I gave him a refund, and he still didn't update the purchase status either.

**Comment by MrMicky-FR** [comment]
The error log is caused by a database connection issue

**Comment by crashzk** [comment]
> The error log is caused by a database connection issue

Ok, I'll check with my web host about the connection issue to see if we can fix it.

Regarding the payment status, shouldn't it be marked as Refund like I did for it, or even Chargeback when the user forces the refund?

Or does Azuriom currently not support status updates based on Refund or Chargeback?

### [EDIT1]
Regarding the connection to the database, as my website and database are on the same host I used `localhost` in the IP, could this cause any connection problems?
