### ISSUE TITLE
Email in PayPal checkout page 

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Shop#189]
I noticed that when a user goes to make a payment via PayPal he has this screen before making the payment.

![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/4e472820-c9e0-46e9-b22d-ece6b37b4cba)

Instead of email, wouldn't you be able to put the name of our website where Azuriom is installed? Or would it be something from PayPal? Both at the bottom and at the top too.

**Comment by MrMicky-FR** [comment]
Can you try with the PayPal Express Checkout integration ? Because I’m not aware of any way to change this in the classic PayPal integration

**Comment by crashzk** [comment]
I understand, PayPal Express Checkout in my country is only for those who have a CNPJ, Juridico in this case. Anyway, thank you in any case.
