### ISSUE TITLE
[REQ] Improvements amount spent on recent payments and top customer

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Shop#190]
![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/231d9e7c-b34a-4547-b3a7-3a7f1bea220f)

Currently, it records all payments, even those that were refunded or chargeback.

It would be interesting to check, if the payment status changes to refund or chargeback, this payment would leave the recent payments table.

Same thing for the **Best Custome**r table, update your total expenses if you have payments marked with refund or chargeback.

**Comment by MrMicky-FR** [comment]
It should already be the case, can you make sure the payments are correctly marked as refunded ?

**Comment by crashzk** [comment]
In fact, the payments showing still show as paid yet. I will be doing some in-depth tests, refunding payments, etc. and letting you know.

**Comment by MrMicky-FR** [comment]
Ok good 👍 Closing this for now as it seems related to #188, but you can @mention me if needed
