### ISSUE TITLE
Discord webhook improvements for products

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Shop#194]
Would it be possible to add the option to send a discord webhook message for each product?

![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/2532b796-debd-4575-8292-2984dafa383e)

Currently, you only have the option to send general. It would be interesting if each product I register in the store had the option to configure its own discord webhook.

This way we can send purchase, refund and chargeback messages to different channels.

It would also be interesting to have a way to edit this message that the webhook will send. Some keys that show product information, such as:
- Value
- Product's name

**Comment by MrJuju0319** [comment]
Hello If possible also add the variables used on the webhook and even be able to have the statistics in the variable tab of which variable was used the most, and be able to reset them if necessary

----
Salut 
Si possible ajouter aussi les variable utilisé sur le webhook et meme pouvoir avoir les statistique dans l'onglet variable de quelle variable a etais le plus utilisé, et pouvoir les reset au besoin

**Comment by MrMicky-FR** [comment]
After some tests, I'm closing this for now, as it adds a lot of complexity to the product page, which is already pretty crowded. A special plugin could be an alternative solution
