### ISSUE TITLE
Questions about purchase limits

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Shop#196]
Would you like to know how the plugin works with the purchase limit?

I would like to configure that the user can only purchase an item that he has already purchased after X period of time.

Example, selling VIP for 30 days, he will only be able to buy this item again after 30 days, is something like this possible?

![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/edd42182-fc04-406f-8366-f9353f859307)

Would this configuration be correct?

**Comment by MrMicky-FR** [comment]
Yes should work fine, but for timed products you might look at subscriptions (see https://github.com/Azuriom/Plugin-Shop/issues/31#issuecomment-1974868836) which might be a better fit for this use case

**Comment by MrMicky-FR** [comment]
About how it works, the plugin will count the number of purchases in the 30 last days (and not on a specific date or something like this)
