### ISSUE TITLE
Proposal to credit our account

### ISSUE THREAD

**Issue by LeSphinx0** [Azuriom/Plugin-Shop#198]
In the offer system that allows you to credit your account with, for example, 5 euros, 10 euros, etc... depending on what the site manager has configured. I propose the possibility of creating an offer that will allow our users to credit their account in a personalized way (therefore according to the number of credit they need).

**Comment by MrMicky-FR** [comment]
This would require a fixed conversion between euros <-> site credits, which is not the goal of offers.

In this case a better solution might be to simply disable website money to directly use the payment gateways
