### ISSUE TITLE
Add expiration for products

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Shop#200]
An option would be interesting so that we can activate/deactivate it so that the product the user purchased is removed from their account.

From what I can see, issues https://github.com/Azuriom/Plugin-Shop/issues/31 will have this feature, but only in subscription products.

If I would like single-purchase products too, for example, I have a product in the store, VIP 30 days.

The user makes the purchase and keeps this VIP active for 30 days, but after 30 days the product will be removed from them, and all the resources they gained by purchasing will also be removed. If you want the resources again, you need to buy the VIP again for 30 days.

This is due to the fact that I don't feel very confident in offering products with automatic subscriptions to users, many may claim that they no longer want to renew after a few months so to speak and that they didn't know that they would need to cancel themselves to stop payments, the charges.

Anyway, this feature of removing the customer's product from the single purchase option would be perfect. We could use the **Period limit** feature that we have to configure for the user to purchase again along with it, that is, if I configure that the user can only purchase again after a period of 30 days when the product has passed 30 days it would be removed from the user and then they could purchase again.

**Comment by MrMicky-FR** [comment]
What about subscriptions with manual renewals ? Like a « renew » button in user profile and/or a mail few days before expiration ? Seems like an easier solution rather than waiting for the expiration then buying the product again

**Comment by crashzk** [comment]
And how would this button << renew >> and/or the email a few days before expiration work?

If the user doesn't click this button to renew, would the product be removed from them? Would you lose access to everything you purchased?

If he does not click on the button to renew and the email does not arrive due to any problem, be it web hosting, SPAM blocking, etc., unregistered email, etc.

**Comment by MrMicky-FR** [comment]
If the user doesn’t renew he would lose access to the subscription, and could always subscribe again

**Comment by crashzk** [comment]
I believe this would be perfect, for now it would resolve my issue.

**Comment by MrMicky-FR** [comment]
<img width="572" alt="image" src="https://github.com/Azuriom/Plugin-Shop/assets/30863452/08c9bc28-8ac3-426d-a402-5fb369079fac">
Closing as it was added as part of #31 🙂
