### ISSUE TITLE
Gift Card not applying when going through payment portal

### ISSUE THREAD

**Issue by OliverP98** [Azuriom/Plugin-Shop#201]
Hello, we have just recently made use of the shop plugin for our website. 

Our Issue is that Gift Cards do not apply when going through payment portals; portals that we are using are PayPal and PayPal express.

**Example1**; a package on the website costs $5 - I have created and applied a gift card of $3, on the shop checkout screen it shows there is $2 to pay, but once you go through to PayPal it's requesting the full $5.

Example 2; a package on the website costs $5 - I have created and applied a gift card of $5, on the shop checkout screen it shows there is $0 to pay, but still requests the user to go through to a payment option, its then requesting the full $5.

If you need more information, please do ask, we have been enjoying the website and its multiple plugins and this is the first issue we have come across.

Thanks

**Comment by MrMicky-FR** [comment]
Hi, it was fixed in https://github.com/Azuriom/Plugin-Shop/commit/e589455d989c47192aa689e24ca7ccd38e42076f, should be released soon on the market
