### ISSUE TITLE
Add Apple Pay through PayPal

### ISSUE THREAD

**Issue by joti-prime** [Azuriom/Plugin-Shop#203]
Please add apple pay if using paypal rest api app:

https://developer.paypal.com/docs/checkout/apm/apple-pay/#link-howitworks

**Comment by MrMicky-FR** [comment]
According to [PayPal documentation](https://developer.paypal.com/docs/checkout/apm/apple-pay/#link-gettingstartedinyourtestingenvironment), you need an [Apple developer account](https://developer.apple.com/) for this integration, which [costs 99$/year](https://developer.apple.com/support/enrollment/). If you can [sponsors us](https://github.com/sponsors/Azuriom) this amount or give us access to an Apple developer account, we could work towards this integration

**Comment by MrMicky-FR** [comment]
Also, otherwise, both [Mollie](https://www.mollie.com/) and [Stripe](https://stripe.com/) support natively Apple Pay

**Comment by joti-prime** [comment]
Hello, you just need an apple developer account for sandbox, not for live:

“Create an Apple Pay sandbox account for testing. You don't need an Apple developer account to go live.“

sS you can make the integration without any problems.

**Comment by MrMicky-FR** [comment]
Well in this case it’s the opposite issue, we don’t have a PayPal business account, which is required for live credentials

**Comment by joti-prime** [comment]
Why you need it to develop it? Same as express/checkout, you need api keys and is implemented express/checkout

**Comment by MrMicky-FR** [comment]
To test the integration during development ? Otherwise how I should debug if I can’t use sandbox (requires Apple developer account) nor live (requires PayPal business account) ?

**Comment by joti-prime** [comment]
But you can use sandbox without business account?

**Comment by MrMicky-FR** [comment]
> “Create an Apple Pay sandbox account for testing. You don't need an Apple developer account to go live.“

In this case seems like you need an Apple developer account (which go back to my [first comment](https://github.com/Azuriom/Plugin-Shop/issues/203#issuecomment-2145761470))

**Comment by joti-prime** [comment]
My argument is that if you used sandbox is because you have a PayPal business account so you can test it with live without apple account.

**Comment by MrMicky-FR** [comment]
For sandbox testing you can use a personal PayPal account, business account is required only to go live. But especially if I had a PayPal business account I wouldn’t have mentioned this as an issue

**Comment by joti-prime** [comment]
You can just create a business account with a few clicks, if not you can use our api keys for testing
