### ISSUE TITLE
Add temporary roles for subscriptions and expiring packages 

### ISSUE THREAD

**Issue by kolya112** [Azuriom/Plugin-Shop#204]
### Description of your suggestion

Hello, is it possible to add to the market, in the package settings menu, the issuance of a group on the site temporarily (for a certain period)? After the time has expired, it will change to the one selected in the package settings or to the default group on the site. Now, as far as I understand, the group on the site is only issued forever.

**Comment by ErrorHunter1** [comment]
I want the same thing.

What do we imagine:
As soon as you buy VIP for 7 days, for example, you get the command in Minecraft and the VIP rank on the website via azlink. But how can it be removed again?

That's why I would like to be able to specify a time for how long the player gets the rank.
