### ISSUE TITLE
Ajouter Starpass comme moyen de paiement

### ISSUE THREAD

**Issue by courat-private** [Azuriom/Plugin-Shop#205]
Bonjour,

Je souhaiterai faire une suggestion plus qu'utile.
Il serait bien d'ajouter le moyen de paiement "Starpass" pour remplacer Dedipass. Nous le savons tous, le support de Dedipass est inactif, et tous les reversements qu'ils nous font prennent un temps fou à venir, de moins en moins de personne ne leurs font confiance, c'est pour cela que cela serait une bonne idée d'ajouter à la place Starpass.

**Comment by MrMicky-FR** [comment]
Due to the large number of different payment methods available, we won't be adding any directly to the shop plugin.

However, new payment methods can be added via a plugin, as explained in the [GitHub README](https://github.com/Azuriom/Plugin-Shop#custom-payment-gateway).
