### ISSUE TITLE
Deactivate offers for a role

### ISSUE THREAD

**Issue by Povotech** [Azuriom/Plugin-Shop#206]
I use the currency of the site and I would like to deactivate the offers for certain roles for example I would like to block purchases of currency for real money for users who are under 18 years old without blocking the entire store because we can have points with votes

**Comment by MrMicky-FR** [comment]
Unfortunately not planned for now as it seems more of an edge case. I would recommand a custom plugin and/or use the terms of use checkbox to "force" users to be 18 years old to purchase on the sore.
