### ISSUE TITLE
Regional Pricing

### ISSUE THREAD

**Issue by OliverP98** [Azuriom/Plugin-Shop#207]
Hi,

A user of ours suggested regional pricing on the shop page, similar to that run by steam and other store fronts. I am not sure of how complex it would be to implement and to ensure there are minimal ways to abuse any bugs.

**Comment by MrMicky-FR** [comment]
What do you mean by regional priciny?

**Comment by OliverP98** [comment]
as currency holds different value around the world, and people have different disposable incomes, countries which have a weaker currency such as those in Asia or South America would pay less due to them being in that region.

Example of this for Stardew Valley shows prices on SteamDB for different regions: https://steamdb.info/app/413150/

**Comment by MrMicky-FR** [comment]
This seems especially hard to implement without a verification system to prevent abuses (users using a VPN or similar systems to use lower-income countries to pay less)

**Comment by OliverP98** [comment]
I guessed as much, and understand why it wouldn't be implemented, thanks for your time
