### ISSUE TITLE
Shop gateway is blocking when gift card brings basket price down to 0.00

### ISSUE THREAD

**Issue by MrZodra** [Azuriom/Plugin-Shop#208]
Hello,
In Azuriom shop currently if a player brings their purchase to 0.00 euro with a giftcard
It still attempts to use the payment gateway which denies it because the purchase is 0.00 euro, which will provide the user an error and it won't claim the giftcard nor provide the purchase.
Could you please change it into that the purchase goes through and they receive an email with purchase confirmation (With used gift card code if possible) and make it skip the gateway when it's 0.00 euro?

**Comment by MrZodra** [comment]
Version shop 1.2.5

**Comment by MrMicky-FR** [comment]
Tested with v1.2.5 and cannot reproduce : the payment is immediately completed if the total is 0 due to a giftcard. Maybe try without a theme to make sure it's not related

**Comment by MrZodra** [comment]
Can not reproduce the error myself either anymore. Probably some other mistake occurring. I will let you know when it occurs again. Issue can be closed o7
