### ISSUE TITLE
Store Bug on Discounts

### ISSUE THREAD

**Issue by fertouille** [Azuriom/Plugin-Shop#209]
Hello ! I noticed a bug (I don't know if I'm the only one) concerning the discounts on the store extension. When I create a discount limited to a certain role, I get an error : 500

**Comment by MrMicky-FR** [comment]
Hello, please send the logs located in the `storage/logs` directory

**Comment by fertouille** [comment]
Ye :

`[2024-08-02 11:49:43] production.ERROR: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '[9]' for column `orioncom_site`.`shop_discounts`.`roles` at row 1 (Connection: mysql, SQL: insert into `shop_discounts` (`name`, `discount`, `roles`, `start_at`, `end_at`, `is_global`, `is_enabled`, `updated_at`, `created_at`) values (VIP, 10, [9], 2024-08-02 11:49:32, 2024-09-19 11:49:32, 1, 1, 2024-08-02 11:49:43, 2024-08-02 11:49:43)) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 22007): SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '[9]' for column `orioncom_site`.`shop_discounts`.`roles` at row 1 (Connection: mysql, SQL: insert into `shop_discounts` (`name`, `discount`, `roles`, `start_at`, `end_at`, `is_global`, `is_enabled`, `updated_at`, `created_at`) values (VIP, 10, [9], 2024-08-02 11:49:32, 2024-09-19 11:49:32, 1, 1, 2024-08-02 11:49:43, 2024-08-02 11:49:43)) at /home/orioncom/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:822)
[stacktrace]`

**Comment by MrMicky-FR** [comment]
The structure of the database is not correct, which may be due to a manual error (in PhpMyAdmin, for example). The simplest immediate solution would be to reinstall Azuriom as it is difficult to assess the extent of the damage
