### ISSUE TITLE
 Allow Guest Payments by Username

### ISSUE THREAD

**Issue by Mardssss** [Azuriom/Plugin-Shop#210]
Currently, users must be logged in to make payments on Azurion. This can be a barrier for users who want to make a purchase without creating an account.

To improve the user experience and increase payment convenience, i am requesting the addition of a feature that allows users to make payments without logging in. This can be achieved by providing an option to enter a username during the payment process.

Here's a proposed implementation:

Add a "Pay by Username" option on the payment page.
When selected, prompt the user to enter the username of the player.
Process the payment as usual.
This feature would enhance the overall payment experience.

**Comment by naverek** [comment]
Its already added I think: https://github.com/Azuriom/Plugin-Shop/issues/155

**Comment by Mardssss** [comment]
no its not yet implemented as far as i know...
you need to be registered to make purchases 
![image](https://github.com/user-attachments/assets/74229770-cf0c-4127-bde9-a432849f52da)

**Comment by MrMicky-FR** [comment]
It’s not already added, but already suggested in #155, which is still open, so no need to keep multiple issues for the same feature request 🙂
