### ISSUE TITLE
Sale not applied with custom price

### ISSUE THREAD

**Issue by Ente3** [Azuriom/Plugin-Shop#212]
If a sales is active on a packet, but you have the custom price (user can choose to pay more) the min the user can use is the origin price and not the sale price
![grafik](https://github.com/user-attachments/assets/4329d69c-293b-4618-859d-863efff745c4)

**Comment by MrMicky-FR** [comment]
Thanks for your patience, this issue has been fixed in v1.2.7 of the shop.
