### ISSUE TITLE
Feature Request: Tax and Fee Addition

### ISSUE THREAD

**Issue by ElDragons** [Azuriom/Plugin-Shop#216]
I hope this message finds you well. I would like to suggest a feature for your shop plugin that could enhance its functionality.

Would it be possible to add an option in the plugin settings that allows users to set a percentage for taxes and fees? The idea is to display the product price without taxes on the store page while showing the total price (including taxes) in the cart. Additionally, it would be great to have an option to decide whether or not to display the tax information on the product page.

I believe this feature would provide a better shopping experience for customers and help store owners manage their pricing more effectively.

Thank you for considering this request!

**Comment by MrMicky-FR** [comment]
Unfortunately, tax management is a complex subject that varies greatly from country to country, and given the large number of different systems it would be too complicated to implement in Azuriom. Some payment methods, like Stripe, offer complete tax management, which seems like a good idea for this use case.
