### ISSUE TITLE
PayFast Payment Gateway

### ISSUE THREAD

**Issue by OryonMax** [Azuriom/Plugin-Shop#219]
### Description of your suggestion

A payment gateway module of https://gopayfast.com/ for Azuriom would be appreciated, it'll help us monetize our upcoming Minecraft Server Network.

### Advantages

There is no way for us to bill at this moment because not a single Minecraft CMS supports our payment gateway.

**Comment by MrMicky-FR** [comment]
As stated in the [README](https://github.com/Azuriom/Plugin-Shop):
> Due to the large number of different payment methods available, we won't be adding any directly to the shop plugin. However, new payment methods can be added via a plugin

**Comment by MrMicky-FR** [comment]
I would suggest either to develop (or find someone to do it) a plugin to add this gateway to Azuriom, or otherwise use one of many already supported gateways

**Comment by OryonMax** [comment]
Alright, no worries then, no other gateway is supported in our country so.
