### ISSUE TITLE
Add icons to (sub)categories names

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Shop#220]
![image](https://github.com/user-attachments/assets/9617cae6-594b-450d-91c0-45753e943162)

![image](https://github.com/user-attachments/assets/345ccaf8-8dfa-49bf-a2ab-c508d641a76e)

**Comment by MrMicky-FR** [comment]
You can already use icon tags in title, like `<i class="bi bi-bank"></i>`

**Comment by crashzk** [comment]
@MrMicky-FR It works, but we have a limitation.

![image](https://github.com/user-attachments/assets/1d8b6c40-f8ed-4d8e-b909-96fc79ddea4a)
`The name field cannot be longer than 50 characters.`

 Would it be possible to increase this character limit in future updates? 75 characters I believe is perfect.

Message I wrote would have 55 in this case.
`<i class="bi bi-person-fill-slash"></i> Unban & Uncomms`

**Comment by crashzk** [comment]
@MrMicky-FR can we open this issue again? Would it be a correct BUG?
