### ISSUE TITLE
Delivery map selection

### ISSUE THREAD

**Issue by reyesdark** [Azuriom/Plugin-Shop#223]
In ARK, it is customary to have several maps, players should choose the map where it would be delivered. Since by default when creating a command, it only gives the option to select a map.

If the player is not online, they do not receive the purchase.

Could you add at the time of purchase to indicate the map where the purchase will be delivered?

**Comment by MrMicky-FR** [comment]
You can use variables in the package to obtain user input (such as map name) during the purchase process

**Comment by reyesdark** [comment]
I mean where the command will be executed. When I started using Azuriom I used the Cloud version, there when creating a command, you could add all the maps where it can be executed. In the other version you must create one command per map.
![image](https://github.com/user-attachments/assets/279787bd-f1de-4d45-9d3b-1d73870bbe80)

**Comment by MrMicky-FR** [comment]
The new way of creating commands (on the screen) gives more flexibility as you can select multiple different maps and different commands for each map, unlike the previous version where the map selection was for all commands.

You can create multiple commands for one map by using the « + » button on the right of the command input

**Comment by reyesdark** [comment]
Yes, I have used it like this, as I show I have multiple commands per map.

Here you see the configured package, there are 3 commands that deliver 3 different items.
![image](https://github.com/user-attachments/assets/3d86fe09-ddc7-479e-a09a-8158bdc12674)

Here you can see the package to buy
![image](https://github.com/user-attachments/assets/1385bd10-009b-48e3-b7ea-c51886b0762e)
![image](https://github.com/user-attachments/assets/3ca1c054-015a-4bd9-b1bb-02ed78c46047)

In the game I don't receive anything.
![image](https://github.com/user-attachments/assets/d68f6ec9-e6fc-4ea0-a65a-f11d638db4d3)
---------------------------

Now when configuring by article, by map.
![image](https://github.com/user-attachments/assets/2879f284-affa-4a99-b060-c3894118258b)

I only deliver one of the three items
![image](https://github.com/user-attachments/assets/67e7d681-8ad8-46e3-805a-87fc38ebe295)


Note: When configuring a single map with multiple commands, only deliver the first command.
![image](https://github.com/user-attachments/assets/471e251b-0024-441e-a692-94660274ea61)

**Comment by MrMicky-FR** [comment]
This is a separate issue, please ask on our Discord
