### ISSUE TITLE
Show package in recent payments and best buyer

### ISSUE THREAD

**Issue by KnightWorldfr** [Azuriom/Plugin-Shop#224]
In the shop settings, we have the option: 
Show the best buyer of the month in the sidebar 
Show the amount in recent payments and best buyer

it might be a good idea to add: 
Show package in recent payments and best buyer (like tebex)

Thank you for reading :)

**Comment by MrMicky-FR** [comment]
Not sure how to implement this as it's common than the user will buy multiple packages at once

**Comment by KnightWorldfr** [comment]
If the user purchases more than one item, the most expensive will be displayed. (like tebex)
