### ISSUE TITLE
Release the purchase of a product after meeting certain requirements

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Shop#232]
I would like to create a product that would have some requirements for players to have access to purchase it.

Example, I have 3 products in total in my store, VIP1, VIP2 and VIP3. User to buy VIP3 must have VIP1 and/or VIP2 active/purchased for X days and still have X position.

Would something like this be possible?

_Note: It would also be interesting for this product to only be visible in the store to users who have the requirements to purchase it._

**Comment by MrMicky-FR** [comment]
It’s already possible, with the required packages field of a product

**Comment by crashzk** [comment]
@MrMicky-FR ok, in this case I configured the necessary packages like this:
![image](https://github.com/user-attachments/assets/7474bd73-5b91-4ef6-bddc-11e0d0c5c94f)


In this case, does he need to have purchased at least one of these products, or does he have to have all the active products in the necessary packages to be able to purchase VIP3?

**Comment by MrMicky-FR** [comment]
I’m not sure, you should try and see :)
