### ISSUE TITLE
TAG on recommended products

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Shop#233]
![image](https://github.com/user-attachments/assets/3c3f79c0-6419-4596-b169-57e2c97bbada)

Would it be possible to have an option that we can enable on the product that indicates that this product is the most recommended, sold in the store.

Something like this: 
![image](https://github.com/user-attachments/assets/3ea7305b-2b7c-439d-b09f-caf12e52d088)

Or would it be something with themes in itself, the theme that needs to have an option like that?

**Comment by MrMicky-FR** [comment]
As you said as it’s something entirely visual, it would be more suited in the theme
