### ISSUE TITLE
It is possible to put multiple accounts PayPal

### ISSUE THREAD

**Issue by LOVOX33** [Azuriom/Plugin-Shop#26]
Hello, I open my forum azuriom for my two two garry's mod servers but we are two to manage them and I would like to know if it is possible to put several PayPal on the means of payment and as its activated separately on my shop, if it is not possible that has the next update this can be added please?

**Comment by MrMicky-FR** [comment]
Hi, thanks for your suggestion :) However it’s not possible with PayPal to split a payment between two accounts. And I think it’s also a really inefficient way to manage payments. The easiest solution would be to just have one PayPal and every months after the servers costs are paid just split the remaining money between you
