### ISSUE TITLE
How can I give you real money with a gift card?

### ISSUE THREAD

**Issue by FabriSoftware** [Azuriom/Plugin-Shop#27]
How can I create a gift card with an amount x of money so that a user can use it in the store? I was looking and I just let you give them points

**Comment by SyFizz** [comment]
Just go to https://YOURSITEHERE/admin/shop/giftcards/create

**Comment by yebanme** [comment]
> Just go to https://YOURSITEHERE/admin/shop/giftcards/create

How to use the gift card after creation
