### ISSUE TITLE
Can you add Alipay for payment?

### ISSUE THREAD

**Issue by yebanme** [Azuriom/Plugin-Shop#28]
[Alipay ](https://intl.alipay.com/?locale=en_US) has a large number of users in Asia and is gradually expanding its influence in the world. Can you add [Alipay ](https://intl.alipay.com/?locale=en_US) as a payment method?

**Comment by tapika** [comment]
Does makes much sense to integrate omnipay (https://github.com/thephpleague/omnipay) - system seems to support both - qiwi and alipay payment methods, with one library it's possible to support quite many different payment methods.

Need some html to write down various payment method selection, but server side code could be more or less payment method neutral.

**Comment by yebanme** [comment]
> Does makes much sense to integrate omnipay (https://github.com/thephpleague/omnipay) - system seems to support both - qiwi and alipay payment methods, with one library it's possible to support quite many different payment methods.
> 
> Need some html to write down various payment method selection, but server side code could be more or less payment method neutral.

This is awesome, can you write a plugin using this library? It might be rude to ask you this way, I can’t use PHP code to write programs

**Comment by MrMicky-FR** [comment]
You can now select additional payment methods for Stripe directly from the plugin dashboard 😀
![78F58D7B-C006-400D-978A-52474EBAA41B](https://user-images.githubusercontent.com/30863452/139525518-96c69e96-c589-4ddb-8298-46b6b052199a.png)
