### ISSUE TITLE
Shop Plugin error 

### ISSUE THREAD

**Issue by maza1009ttv** [Azuriom/Plugin-Shop#47]
I have a problem with the shop plugin.
When paying with Paypal the money is transferred but in the dashboard appears an error and the commands are not executed. When I offer something for free it works.
What can be the reason for this?

**Comment by MrMicky-FR** [comment]
Hi, can you send the logs located in `storage/logs` ?

**Comment by maza1009ttv** [comment]
I think I have found the error. Did not think about the logs. Thanks for the tip

**Comment by lauretandretheo** [comment]
Hello how did you find, I have same issue
