### ISSUE TITLE
Allow to delete all the content of the Store in one click

### ISSUE THREAD

**Issue by Shykuzo** [Azuriom/Plugin-Shop#48]
It would be nice to be able to remove all the products, all the categories, ... from our store in one click.

Either by adding a button in the "Settings" category of the store in the Admin panel or by adding a button in a new category.

If possible, it would be nice to have several buttons such as :
  - Delete all products.
  - Delete all offers.
  - Delete all categories.
  - Delete all discounts.
  - Delete all the content of the store.

**Comment by MrMicky-FR** [comment]
Hi, thanks for your suggestion, but I'm not sure to see in which case it would be useful ?

Also if you need to quickly clear all products/offers/etc you can clear (and not delete!) the table `shop_packages`/`shop_offers`/etc with the following SQL command :
```sql
TRUNCATE TABLE `shop_packages`;
```
