### ISSUE TITLE
Add customs option on products.

### ISSUE THREAD

**Issue by K1Mst** [Azuriom/Plugin-Shop#53]
Hi, maybe you can make something to have dynamics  shop products  with customs options maybe managed in another tab and those options could be asked to customer before adding product to cart and used after it in commands with like variables?
**that would be awesome** and I think/hope really useful for a lot of people!! thanks

**Comment by HC-Emro** [comment]
Il le faut à tout prix, je suis prêt à payer !

**Comment by YelehaUwU** [comment]
How's it looking with this? It's really needed for a proper store.

**Comment by MrMicky-FR** [comment]
Please use reactions for promoting suggestions instead of comments. Like all suggestions there is no ETA, but the project is open-source so feel free to open a pull-request or [sponsor us](https://github.com/sponsors/Azuriom) to help us adding new features.

**Comment by MrMicky-FR** [comment]
Added in version 1.2.3 of the shop 🚀
