### ISSUE TITLE
Système d'abonnement

### ISSUE THREAD

**Issue by yenejs** [Azuriom/Plugin-Shop#62]
Salut, j'ai une question, serait-ce possible de mettre un système **d'abonnement** sur le système Shop car je suis à la recherche de celui-ci.

**Exemple ;**
- Si une personne achète un VIP de 1 mois sur mon serveur, j'aimerais que le VIP se supprime automatiquement après 1 mois.

Je pense que beaucoup de personnes souhaiteraient posséder ce système-là car il est très utile pour les serveurs tel que Garry's Mod, Minecraft et d'autres...
Si vous le faites merci bien et au revoir. 👋

**Comment by MrMicky-FR** [comment]
Pour les serveurs Minecraft c’est possible de le faire avec des permissions temporaires, par exemple en utilisant [LuckPerms](https://luckperms.net)

Sinon pour le renouvellement automatique il y a déjà l’issue #31
