### ISSUE TITLE
Page de donation

### ISSUE THREAD

**Issue by SterwimO** [Azuriom/Plugin-Shop#68]
Ajouté un système de donation au plugin (en plus ou non de la boutique) avec les différents paiement qui existe sur ce plugin.

**Comment by BrayaanPS** [comment]
Wouldn't it be better to add packages with the option to choose the amount of money to pay? (You can name the package Donation)

**Comment by SterwimO** [comment]
If you want to add a package you have to add a category so for donations it's a bit ridiculous to create for example a category Donation and inside a single package Donation

**Comment by MrMicky-FR** [comment]
IMHO this would be more suitable in a separate plugin
