### ISSUE TITLE
Auto Réduction ????

### ISSUE THREAD

**Issue by Raphael716** [Azuriom/Plugin-Shop#76]
Salut, j'ai un gros problème sur ma boutique, sa donne des réductions alors que je ne les ai pas mises ! À aucun moment il n'y a de réduction nulle part dans ma boutique. Quelqu'un peux m'aider

![image](https://user-images.githubusercontent.com/69059320/183800824-5d6e43bc-0c0c-49e4-b8eb-7d990dcefb90.png)
![image](https://user-images.githubusercontent.com/69059320/183800830-d6cc9e37-c5cb-4f9e-b2d5-e33d8bc5347c.png)

**Comment by MrMicky-FR** [comment]
Inutile de poser la même question deux fois sur Discord et sur GitHub... Sinon il suffit de désactiver l'option pour cumuler les achats dans l'édition de la catégorie
