### ISSUE TITLE
Can you add Monobank for payment?

### ISSUE THREAD

**Issue by CASH1307** [Azuriom/Plugin-Shop#78]
Can you add Monobank for payment? Currently, due to the difficult situation in Ukraine, most payment methods do not work. Currently, only Monobank and LiqPay are good methods for online payment, but LiqPay is only available for legal entities. So MonoBank is a pretty good option, I can help with testing

**Comment by Javdu10** [comment]
Hi, just like #23 and #74 and probably some others... If you want another provider you would need to implement it yourself or pay someone to do it. You will find relevant info in others issues.

**Comment by MrMicky-FR** [comment]
Hi, thanks for your suggestion :)

As pointed by @Javdu10 in the linked issues, unfortunately it would be too complicated for us to add and test country-specific payment gateways in the shop for every countries.

The best solution would be to create a small plugin to add this payment method, like we did for Dedipass (a french payment gateway) with this plugin: https://github.com/Azuriom/Plugin-DedipassPayment.
