### ISSUE TITLE
Midtrans Payment

### ISSUE THREAD

**Issue by ufarufar** [Azuriom/Plugin-Shop#95]
please add midtrans payment for indonesian payment https://midtrans.com/ here the website

**Comment by MrMicky-FR** [comment]
Hi, thanks for your suggestion :)

Unfortunately it would be too complicated for us to add and test country-specific payment gateways in the shop for every countries.

The best solution would be to create a small plugin to add this payment method, like we did for Dedipass (a french payment gateway) with this plugin: https://github.com/Azuriom/Plugin-DedipassPayment.
